[project]
name = "schemai-builder"
version = "0.1.0"
description = "AI first electrical scheme builder with LLM and TTS"
readme = "README.md"
authors = [
    { name = "theMladyPan", email = "stanislav@rubint.sk" }
]
requires-python = ">=3.14"
dependencies = [
    "cairosvg>=2.9.1",
    "fastapi[standard]>=0.141.1",
    "logfire[fastapi]>=5.1.0",
    "pydantic>=2.13.5",
    "pydantic-ai>=2.44.0",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
schemai-builder = "schemai_builder:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
